// <auto-generated/>
using System;
using UnityEngine.Events;

namespace SoVariableTool
{

    // <auto-generated/>
    [Serializable]
    public class UnitUnityEvent : UnityEvent<SoVariableTool.Unit>, IDynamicEventUseable {}


}
