// <auto-generated/>
using System;
using UnityEngine.Events;

namespace SoVariableTool
{

    // <auto-generated/>
    [Serializable]
    public class Int32UnityEvent : UnityEvent<System.Int32>, IDynamicEventUseable {}


    // <auto-generated/>
    [Serializable]
    public class SingleUnityEvent : UnityEvent<System.Single>, IDynamicEventUseable {}


    // <auto-generated/>
    [Serializable]
    public class DoubleUnityEvent : UnityEvent<System.Double>, IDynamicEventUseable {}


    // <auto-generated/>
    [Serializable]
    public class StringUnityEvent : UnityEvent<System.String>, IDynamicEventUseable {}


    // <auto-generated/>
    [Serializable]
    public class BooleanUnityEvent : UnityEvent<System.Boolean>, IDynamicEventUseable {}


}
