// <auto-generated/>
using System;
using UnityEngine;

namespace SoVariableTool
{

    // <auto-generated/>
    [CreateAssetMenu(fileName = "event_Boolean", menuName = "SoVariableTool/ScriptableEvents/Boolean")]
    public class BooleanScriptableEventObject : ScriptableEventObject<Boolean, BooleanUnityEvent>
    {
    }

}