// <auto-generated/>
using System;
using UnityEngine;

namespace SoVariableTool
{

    // <auto-generated/>
    [CreateAssetMenu(fileName = "event_Double", menuName = "SoVariableTool/ScriptableEvents/Double")]
    public class DoubleScriptableEventObject : ScriptableEventObject<Double, DoubleUnityEvent>
    {
    }

}
