// <auto-generated/>
using System;
using UnityEngine;

namespace SoVariableTool
{

    // <auto-generated/>
    [CreateAssetMenu(fileName = "event_Int32", menuName = "SoVariableTool/ScriptableEvents/Int32")]
    public class Int32ScriptableEventObject : ScriptableEventObject<Int32, Int32UnityEvent>
    {
    }

}
