// <auto-generated/>
using System;
using UnityEngine;

namespace SoVariableTool
{

    // <auto-generated/>
    [CreateAssetMenu(fileName = "event_Single", menuName = "SoVariableTool/ScriptableEvents/Single")]
    public class SingleScriptableEventObject : ScriptableEventObject<Single, SingleUnityEvent>
    {
    }

}
