// <auto-generated/>
using System;
using UnityEngine;

namespace SoVariableTool
{

    // <auto-generated/>
    [CreateAssetMenu(fileName = "event_String", menuName = "SoVariableTool/ScriptableEvents/String")]
    public class StringScriptableEventObject : ScriptableEventObject<String, StringUnityEvent>
    {
    }

}
