// <auto-generated/>
using System;
using UnityEngine;

namespace SoVariableTool
{

    // <auto-generated/>
    [CreateAssetMenu(fileName = "event_Unit", menuName = "SoVariableTool/ScriptableEvents/Unit")]
    public class UnitScriptableEventObject : ScriptableEventObject<Unit, UnitUnityEvent>
    {
    }

}
